development:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  database: myzenrx
  

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  database: mydb
  host: localhost 
  pool: 5
  timeout: 5000
